/**
 * Domain type for a user record.
 */
export interface User {
  id: string;
  name: string;
  email: string;
  role: UserRole;
  createdAt: string;
}

/**
 * Roles a user can have within the application.
 */
export type UserRole = "admin" | "member" | "guest";

/**
 * Payload accepted when creating a new user.
 * `id` and `createdAt` are generated by the server.
 */
export type CreateUserInput = Omit<User, "id" | "createdAt">;

/**
 * Payload accepted when updating an existing user.
 * Every field is optional so callers can send partial updates.
 */
export type UpdateUserInput = Partial<CreateUserInput>;
